# Generated by Django 2.2.3 on 2020-02-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200214_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
